name: style code checks

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Install python
        uses: action/setup-python@v2
        with:
          python-version: 3.10
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run flake8   
        run: flake8
